name: Cookie CI
on: 
  push: 
    branches: 
      - "feature/**"
# env:
#   docker_username: ${{ secrets.DOCKER_USERNAME }}
#   docker_password: ${{ secrets.DOCKER_PASSWORD }}
#   GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone down
        uses: actions/checkout@v2
      - name: Clone down
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Build:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: build backend
        run: cd backend && go build && cd ..
      - name: build frontend
        run: cd frontend && go build
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with: 
          name: code
          path: .
  # Docker-image:
  #   runs-on: ubuntu-latest
  #   needs: [Build]
  #   steps: 
  #     - name: Download repo
  #       uses: actions
  Frontend-test:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v1
        with:
          name: code
          path: .
      - name: Execute frontend test
        run: cd frontend && go test